# Generated by Django 4.0.5 on 2022-07-04 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0002_alter_department_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True)),
                ('product_exp', models.DateField(auto_created=True)),
                ('product_mfg', models.DateField(auto_created=True)),
                ('product_name', models.CharField(default='', max_length=150)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('deleted_at', models.BooleanField(default=1)),
                ('product_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
    ]
