# Generated by Django 4.0.5 on 2022-07-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_deleted_at'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='department.department'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_mfg',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
