# Generated by Django 4.0.5 on 2022-07-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_product_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_department',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_amount',
            field=models.IntegerField(default=0),
        ),
    ]
