# Generated by Django 4.0.5 on 2022-07-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_product_department_product_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_amount',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_exp',
            new_name='expiry',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_mfg',
            new_name='manufacturing',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
