# Generated by Django 4.0.5 on 2022-07-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_amount_product_amt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiry',
            field=models.DateField(auto_created=True, blank=True),
        ),
    ]
