# Generated by Django 4.0.5 on 2022-07-15 06:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0002_alter_doctor_mobile'),
        ('product', '0007_alter_product_created_at_alter_product_expiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('doctor_id', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=150)),
                ('mobile', models.EmailField(default='', max_length=150)),
                ('due_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('deleted_at', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('order_date', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('bill_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_amt', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payable_amt', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('paid_amt', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payment_data', models.TextField(default='')),
                ('payment_status', models.CharField(default='', max_length=20)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('deleted_at', models.BooleanField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='seller.customer')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('order_qty', models.IntegerField(default=0)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('deleted_at', models.BooleanField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='seller.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product')),
            ],
        ),
    ]
