# Generated by Django 4.0.5 on 2022-06-11 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(default='', max_length=150)),
                ('password', models.CharField(default='', max_length=150)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('mobile', models.IntegerField()),
                ('profile_img', models.ImageField(default='profile-img.jpg', upload_to='')),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(default='', max_length=150)),
                ('dist', models.CharField(default='', max_length=150)),
                ('state', models.CharField(default='', max_length=150)),
                ('country', models.CharField(default='', max_length=150)),
                ('pwd_reset', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
