# Generated by Django 4.0.5 on 2022-06-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pincode',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='staff',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
