# Generated by Django 4.0.5 on 2022-06-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='about_user',
            field=models.TextField(default=''),
        ),
    ]
