# Generated by Django 4.0.5 on 2022-06-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_staff_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='updated_at',
        ),
    ]
