# Generated by Django 4.0.5 on 2022-06-13 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_staff_created_at_alter_staff_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='staff',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
