# Generated by Django 4.0.5 on 2022-06-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_alter_staff_created_at_alter_staff_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='created_at',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='staff',
            name='updated_at',
            field=models.DateField(default=''),
        ),
    ]
