# Generated by Django 4.0.5 on 2022-06-13 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_alter_staff_created_at_alter_staff_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 14, 55, 9, 616955, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 14, 55, 9, 616955, tzinfo=utc)),
        ),
    ]
