# Generated by Django 4.0.5 on 2022-06-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_alter_staff_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_img',
            field=models.ImageField(default='profileImage/profile-img.jpg', upload_to='profileImage/'),
        ),
    ]
