# Generated by Django 4.0.5 on 2022-06-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_alter_staff_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='user_role',
            field=models.CharField(default='', max_length=30),
        ),
    ]
