# Generated by Django 4.0.5 on 2022-06-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_staff_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user_role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Seller', 'Seller')], max_length=30),
        ),
    ]
