# Generated by Django 4.0.5 on 2022-06-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_alter_staff_gender_alter_staff_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='login_attempt',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
