# Generated by Django 4.0.5 on 2022-06-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_staff_login_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='login_attempt',
            field=models.IntegerField(default=0),
        ),
    ]
