# Generated by Django 4.0.5 on 2022-06-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_alter_staff_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='user_role',
            field=models.CharField(choices=[('Owner', 'owner'), ('Seller', 'seller')], max_length=30),
        ),
    ]
