# Generated by Django 4.0.5 on 2022-06-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_alter_staff_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='user_role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Seller', 'Seller')], max_length=30),
        ),
    ]
