# Generated by Django 4.0.5 on 2022-06-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0029_staff_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='deleted_at',
            field=models.BooleanField(default=1),
        ),
    ]
