# Generated by Django 4.0.5 on 2022-06-30 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0002_alter_department_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('name', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=150)),
                ('mobile', models.IntegerField(default=0)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('deleted_at', models.BooleanField(default=1)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
    ]
