# Generated by Django 4.0.5 on 2022-06-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='deleted_at',
            field=models.BooleanField(default=1),
        ),
    ]
